// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkS3LdzhZMW7Tzka9Yia54kL8WXR9llRY',
    appId: '1:947793939815:web:36805413993ecba10433c2',
    messagingSenderId: '947793939815',
    projectId: 'personalblog-a72a3',
    authDomain: 'personalblog-a72a3.firebaseapp.com',
    databaseURL: 'https://personalblog-a72a3-default-rtdb.firebaseio.com',
    storageBucket: 'personalblog-a72a3.firebasestorage.app',
    measurementId: 'G-7G03B9KPPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRIHlLJqx6Ba3SRAYoFrjyjf_wLri1L2Q',
    appId: '1:947793939815:android:9a57a598c01cad130433c2',
    messagingSenderId: '947793939815',
    projectId: 'personalblog-a72a3',
    databaseURL: 'https://personalblog-a72a3-default-rtdb.firebaseio.com',
    storageBucket: 'personalblog-a72a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-cbSGxUP6K-430W31G5fjNoJ6d2M8G9g',
    appId: '1:947793939815:ios:5086fade1ff576550433c2',
    messagingSenderId: '947793939815',
    projectId: 'personalblog-a72a3',
    databaseURL: 'https://personalblog-a72a3-default-rtdb.firebaseio.com',
    storageBucket: 'personalblog-a72a3.firebasestorage.app',
    iosBundleId: 'com.example.reedsblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-cbSGxUP6K-430W31G5fjNoJ6d2M8G9g',
    appId: '1:947793939815:ios:5086fade1ff576550433c2',
    messagingSenderId: '947793939815',
    projectId: 'personalblog-a72a3',
    databaseURL: 'https://personalblog-a72a3-default-rtdb.firebaseio.com',
    storageBucket: 'personalblog-a72a3.firebasestorage.app',
    iosBundleId: 'com.example.reedsblog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwvEMSxi_nD5Eu4Ze2aQQ6C7_VnNOX1R4',
    appId: '1:947793939815:web:c499a8955a0318650433c2',
    messagingSenderId: '947793939815',
    projectId: 'personalblog-a72a3',
    authDomain: 'personalblog-a72a3.firebaseapp.com',
    databaseURL: 'https://personalblog-a72a3-default-rtdb.firebaseio.com',
    storageBucket: 'personalblog-a72a3.firebasestorage.app',
    measurementId: 'G-JDM225BFD6',
  );
}
